baseURL = 'https://techblog.onpoint.vn/'
languageCode = 'en-us'
title = 'OnPoint Tech Blog'
theme = 'bookworm'

# post pagination
paginate = "7"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "G-S0MXF6F38B" # example : UA-123-45
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.80.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true


############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
# [[params.plugins.css]]
# link = "https://fonts.googleapis.com/css2?family=Noto Serif:wght@400;600;700&display=swap"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@400;600;700&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "https://unpkg.com/eva-icons"

# site variables
[params.variables]
font_content = "Mulish"
font_primary = "Mulish"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#f9f9f9"
black = "#000000"
dark = "#152035"
gray = "#313b3f"
light_gray = "#666666"
light = "#FAFAFA"
color_primary = "#ff9700"

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_height = "35px"
favicon = "images/favicon.png"
# Meta data
description = "OnPoint is the largest E-commerce enabler in Vietnam, providing end-to-end services, helping brands to accelerate and become more successful online in Vietnam and SEA region"
author = "Dung Nguyen"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Blog by OnPoint Team. Theme by [Gethugothemes](https://gethugothemes.com/)"

# sidebar
sidebar = false

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "#" # replace this url with yours
mailchimp_form_name = "#" # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
[[menu.main]]
weight = 1
url = "/"
name = "Blog"

[[menu.main]]
weight = 2
url = "tags/"
name = "Tags"

[[menu.main]]
weight = 3
url = "about"
name = "About us"

[[menu.main]]
weight = 4
url = "https://www.onpoint.vn/careers/"
name = "We are hiring"

# [[menu.main]]
# weight = 4
# url = "contact"
# name = "Contact"


# [[menu.main]]
# weight = 5
# url = "#"
# name = "More"
# hasChildren = true

#   [[menu.main]]
#   parent = "More"
#   weight = 1
#   url = "author/"
#   name = "Author"
  
#   [[menu.main]]
#   parent = "More"
#   weight = 2
#   url = "tags/"
#   name = "Tags"
  
#   [[menu.main]]
#   parent = "More"
#   weight = 3
#   url = "categories/"
#   name = "Category"
  
  # [[menu.main]]
  # parent = "Pages"
  # weight = 4
  # url = "elements/"
  # name = "Elements"
  
  # [[menu.main]]
  # parent = "Pages"
  # weight = 5
  # url = "privacy/"
  # name = "Privacy"
  
  # [[menu.main]]
  # parent = "Pages"
  # weight = 6
  # url = "terms-conditions/"
  # name = "Terms & Conditions"

############################# Footer Menu ########################
[[menu.footer]]
weight = 1
url = "about/"
name = "About me"

[[menu.footer]]
weight = 2
url = "author/"
name = "Authors"


[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
# style = 'algol'
style = 'dracula'
tabWidth = 4